Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 25
MethodLength:
  Max: 35
Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'Gemfile'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'test/test_helper.rb'
