Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 20
Metrics/ClassLength:
  Max: 120
MethodLength:
  Max: 20
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'Gemfile'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'test/test_helper.rb'
